# Application
spring.application.name=file-upload-lookup
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.fileuploadlookup=DEBUG


#api_gateway_url = "https://z07qmg52sb.execute-api.us-west-2.amazonaws.com"

#ALB domain: file-upload-alb-351799307.us-west-2.elb.amazonaws.com

#SSH to EC2: ssh -i ~/.ssh/id_rsa ec2-user@34.219.173.42        ->public IP